### PR TITLE
Fix memory bug adding some free() methods

### LINKED ISSUE #54: test memory and CPU usage
Is important to know how much memory and CPU is used by fievel, at least in `capture_file` method (which is for now the only one that we can test).

We need to test it in different scenarios: one or several .pcap files, which differ on how many packets per second are processed.

### PR DESCRIPTION
**Pull request by camilog**
Fixes #54

### CODE REVIEW

**Comment by eacha** [comment]
LGTM

File: src/main.c [hunk 1]
```diff
@@ -353,6 +353,7 @@ static void deinit(struct capture_options *capture_options, thread_data_t **t_da
             mcb_remove_consumer(data->buffer, t_data[i]->consumer_id);
         }
         fievel_delete_prer(data->prer_list[i]);
+        free(t_data[i]);
```
Comment (fmontoto) [inline src/main.c]: There is a check above (t_data != NULL), could t_data be NULL?
If that's the case this could lead to undefined behavior.

Maybe move this inside the if?

File: src/lua_prer.c [hunk 2]
```diff
@@ -194,7 +195,9 @@ static void pushpacket(lua_State *L, packet_t *packet) {
 	lua_newtable(L); // queries array in -2, query in -1
 	// table, key, array, idx, query
 	lua_pushstring(L, "qname");
-	lua_pushstring(L, ldns_rdf2str(ldns_rr_owner(rr)));
+	char *rr_owner = ldns_rdf2str(ldns_rr_owner(rr));
```
Comment (fmontoto) [inline src/lua_prer.c]: Can you check the indentation here, it doesn't look right.

**Comment by camilog** [comment]
@fmontoto check it now

**Comment by fmontoto** [comment]
LGTM
